name: Job Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Install Chrome
        run: |
          # Download Google's Linux signing key and add it to a keyring file
          curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/google-linux-signing-key.gpg > /dev/null
          # Add the Chrome repository with the signed-by option
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
      - name: Install ChromeDriver
        run: |
          # Print the Chrome version for debugging
          echo "Running: google-chrome-stable --version"
          google-chrome-stable --version
          
          # Get Chrome version and extract three-part version
          CHROME_VERSION=$(google-chrome-stable --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "CHROME_VERSION: $CHROME_VERSION"
          
          # Extract the major version (e.g., "134")
          MAJOR_VERSION=${CHROME_VERSION%%.*}
          echo "MAJOR_VERSION: $MAJOR_VERSION"
          
          # Use the major version to get the correct ChromeDriver version
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${MAJOR_VERSION}")
          echo "CHROMEDRIVER_VERSION: $CHROMEDRIVER_VERSION"
          
          # Download and install ChromeDriver
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run job scraper
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          AIRTABLE_URL: ${{ secrets.AIRTABLE_URL }}
        run: python import_requests.py
